#!/usr/bin/bash
# curl -F username=20174227013 -F password=dHJhamVwbDEyMw== http://a.suda.edu.cn/index.php/index/login

function networkAndFtp(){
    timeout=5
    target=www.baidu.com

    ret_code=`curl -I -s --connect-timeout $timeout $target -w %{http_code} | tail -n1`

    if [ "x$ret_code" != "x200" ] 
    then
        curl -F username=20174227013 -F password=dHJhamVwbDEyMw== http://a.suda.edu.cn/index.php/index/login
        echo "reconnect the web at " `date` >> ~/git-repo/ljp/linux/sudawg/webinfo.log
    fi
}

while true
do
    networkAndFtp
done
